language: java

jdk: oraclejdk8

cache:
  directories:
    -$HOME/.m2
      
script:
 - mvn verify -Ptest

notifications:
  email:
    recipients:
      - madsjuste89@gmail.com
    on_success: never 
    on_failure: always 

 
after_succes:
      - mvn tomcat7:deploy -Premote
     

