language: java

jdk: oraclejdk8

cache:
  directories:
    -$HOME/.m2
      
script:
 - mvn verify -Ptest
notifications:
  slack:
      on_failure: -always
      on_succes: -always
      after_succes:
      -mvn tomcat7:deploy -Pdeployremote




