language: java

jdk: oraclejdk8

cache:
  directories:
    -$HOME/.m2
      
script:
 - mvn verify -Ptest

notifications:
  email:
    recipients:
      - one@example.com
      - other@example.com
    on_success: never # default: change
    on_failure: always # default: always



