language: java

jdk: oraclejdk8

cache:
  directories:
    -$HOME/.m2

notifications:
  slack:
    email:
      Madsjuste89@gmail.com

      on_failure: always
      on_succes: always

after_succes:
  mvn tomcat7:deploy -Pdeployremote

script:
  mvn test
  mvn verify
  mvn verify -Ptest



