language: java

jdk: oraclejdk8

cache:
  directories:
    -$HOME/.m2

notifications:
  slack:
    email:
      -Madsjuste89@gmail.com

      on_failure: -always
      on_succes: -never
      after_succes:
      -mvn tomcat7:deploy -Pdeployremote

script:
 -mvn verify -Ptest



